### ISSUE TITLE
The app works, but old data is showed

### ISSUE THREAD

**Issue by adeleglise** [bnjbvr/kresus#57] opened 2015-04-01 09:03 UTC
Hi,

I've updated the app (now using 0.4.3) and I can connect to my account.

But all the data in the app are from 2014, the synchronization works with no errors.

**Comment by bnjbvr** [comment] 2015-04-04 14:19
Hi,

That is strange.

- Was it already the case with the previous version of kresus, or is it new?
- When you connect to your bank website, do you only see old data from 2014?
- When you say you're seeing data from 2014 only, in which section are you browsing? (list of transactions, charts, etc.)
- Can you spot something weird in the server log, when doing the synchronization?
- Can you spot something weird in the developers console, when launching the app (in particular, make sure to force reload with Ctrl F5)?

**Comment by bnjbvr** [comment] 2015-04-28 20:42
Any news, @adeleglise ?

**Comment by adeleglise** [comment] 2015-05-04 09:12
Hi bnjbvr, I'm sorry I can't give a feedback for now. I will try to do it this week.

**Comment by nicofrand** [comment] 2015-09-02 07:54
This was probably a duplicate of https://github.com/bnjbvr/kresus/issues/150 ?

**Comment by bnjbvr** [comment] 2015-10-11 15:36
Any news here, @adeleglise ?

**Comment by bnjbvr** [comment] 2015-11-16 09:28
No answer since May 4th, closing. Feel free to reopen if the issue is still present nowadays.

**Closed by bnjbvr** 2015-11-16 09:28 UTC
Labels: bug, question
